name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v2.1.3, etc.

jobs:
  publish:
    runs-on: ubuntu-22.04  # Specifies the exact Ubuntu version

    permissions:
      contents: write  # Grants write access to repository contents, including releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use the latest major version for stability

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest major version
        with:
          python-version: '3.11'  # Specify your desired Python version
          cache: 'pip'             # Enables pip caching

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine  # Install the latest versions

      - name: Install Dependencies
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install .

      - name: Run Tests
        run: |
          python -m unittest discover
        # Adjusted to discover tests in default directories

      - name: Build Package
        run: |
          python -m build
        # This creates both sdist and wheel in the 'dist/' directory

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
        # Ensure 'PYPI_TOKEN' is set in your repository secrets

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1  # Updated to a maintained action
        with:
          tag_name: ${{ github.ref_name }}          # Correctly extracted tag name
          name: Release ${{ github.ref_name }}      # Correctly extracted release name
          body: "Automated release of `${{ github.ref_name }}`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 'GITHUB_TOKEN' is automatically provided, but specifying it ensures compatibility
